#!/bin/bash
lualatex --shell-escape article
bibtex article
lualatex --shell-escape article
lualatex --shell-escape article

# rm article.aux
# rm article.auxlock
# rm article.bbl
# rm article.blg
# rm article.log
# rm article.pag

rm article-figure0.dep
rm article-figure0.dpth
rm article-figure0.log
rm article-figure0.md5
rm article-figure0.pag

pdfcrop article-figure0.pdf fig.pdf
# pdftk article-figure0.pdf cat 1 output fig.pdf
rm article-figure0.pdf
