#!/bin/bash
lualatex --shell-escape fig

rm fig.aux
rm fig.auxlock
rm fig.len
rm fig.log
rm fig.nav
rm fig.out
rm fig.snm
rm fig.toc
rm fig-figure0.dep
rm fig-figure0.dpth
rm fig-figure0.len
rm fig-figure0.log
rm fig-figure0.md5

pdftk fig-figure0.pdf cat 1 output fig.pdf
rm fig-figure0.pdf
